# Customized Caddy log format with all headers removed, except user agent and referer which are placed at top level
log-format {"ts":"%x.%^","request":{"client_ip":"%h","method":"%m","host":"%v","uri":"%U"},"duration": "%T","size": "%b","status": "%s","referer":"%R", "user_agent":"%u"}
time-format %s
date-format %s
log-file /var/log/caddy/puzlinghome.log

static-file .css
static-file .js
static-file .woff2
static-file .svg
static-file .png
static-file .jpg
static-file .mp3

# puzl.ing does not use query string
no-query-string true

# This does not work as expected
# https://github.com/allinurl/goaccess/issues/2562
ignore-referrer puzl.ing

# Unique visitors is a meaningless metric since the site is behind cloudflare
ignore-panel VISITORS
#ignore-panel REQUESTS
#ignore-panel REQUESTS_STATIC
#ignore-panel NOT_FOUND
ignore-panel HOSTS
#ignore-panel OS
#ignore-panel BROWSERS
ignore-panel VISIT_TIMES
ignore-panel VIRTUAL_HOSTS
#ignore-panel REFERRERS
#ignore-panel REFERRING_SITES
ignore-panel KEYPHRASES
ignore-panel STATUS_CODES
ignore-panel REMOTE_USER
ignore-panel CACHE_STATUS
ignore-panel GEO_LOCATION
ignore-panel MIME_TYPE
ignore-panel TLS_TYPE

# Ignore redirect /page to /page/
ignore-status 308

# Persist aggregate data past log deletion
db-path /var/log/caddy/goaccess-db
persist true
restore true
